### ISSUE TITLE
Evaluate accuracy of estimate area extent script

### ISSUE THREAD

**Issue by mindyls** [NRLMMD-GEOIPS/geoips#266]
# Requested Update

### Description
Given intermittently inaccurate sectors generated using estimate_area_extent:

https://github.com/NRLMMD-GEOIPS/geoips/issues/262

Evaluate the accuracy of the function used to generate these sectors:

https://github.com/NRLMMD-GEOIPS/geoips/blob/254bb6ff023388ce97e49907239c54a27a6f9be1/geoips/sector_utils/estimate_area_extent.py#L22

Also related to 

https://github.com/NRLMMD-GEOIPS/geoips/issues/261

### Background and Motivation
* Want to ensure estimate area extent is accurate, given Jeremy noticed some sectors were too small when created using estimate area extent.

### Alternative Solutions
*  [ OPTIONAL: If appropriate, list alternative fixes that could be considered]
  
### Environment
*  [ IF APPROPRIATE: Corresponding repository versions ]

### Code to demonstrate issue
*  [ IF APPROPRIATE: Can include steps here to identify/demonstrate bug fix or desired feature ]

### Checklist for Completion
* [ ]

**Comment by jsolbrig** [comment]
I think that I understand what is going on here. For the most part I think we can get away from using this script entirely. We no longer need to specify area_extent in `area_definition` defined sectors. Instead we can use `center` which provides enough information to complete the AreaDefinition and not result in a DynamicAreaDefinition.

We may want to take the "corners" part of this and move it into `geoips/interfaces/yaml_based/sectors.py`. It is going to need to be reworked, though.

Currently, this routine doesn't work well because it is trying to compute distance from the center point using the haversine distance. It does not take into account the warping that the projection adds. To correctly compute the area_extent based on the corner coordinates, we will need to pass the corner coordinates through the projection algorithm.

**Comment by jsolbrig** [comment]
Closing in favor of #284
