### ISSUE TITLE
Include Support for GOES GLM

### ISSUE THREAD

**Issue by thiemep** [NRLMMD-GEOIPS/geoips#35]
# Requested Update

### Description
Current GeoIPS does not support the GOES Geostationary Lightning Mapper. Other operational requirements on certain systems require the inclusion of the GLM!

### Background and Motivation
Other commercial product generation and viewing programs already support GLM!

[ ] Add product for GLM
[ ] Add to GOES R series spacecraft in documentation

**Comment by jsolbrig** [comment]
This needs to be addressed for OVERCAST. It looks like Satpy has a GLM reader implemented, so maybe we can just use that similar to what was done for L2 ABI data.

**Comment by cpcamacho** [comment]
@jsolbrig, the GLM reader available in satpy is not for the ABI GLM-L2-LCFA files. The satpy GLM reader is for reading the output of `glmtools`, which converts the LCFA data into a gridded product.

See this following issue for more details:
https://github.com/pytroll/satpy/issues/1149

And I believe this is the `glmtools` repo:
https://github.com/deeplycloudy/glmtools

**Comment by mindyls** [comment]
@evrose54 leave a comment on where you're at with this link to the internal CIRA gitlab.

**Comment by evrose54** [comment]
I've just got to the point where I have a working algorithm for Group Extent Density and Flash Extent Density (FED/GED), for the goes_east sector. Currently, this algorithm only works for that sector, since I have to have a grid pre-computed to calculate both GED and FED. This is because algorithms of the type 'xarray_dict_to_xarray' aren't supported under the product family 'interpolator_algorithm_colormapper'. If it was, I could interpolate first, then use that grid to calculate both GED and FED at runtime. The link for where all of this code is hosted is at https://bear.cira.colostate.edu/overcast/geoips_glm.

**Comment by jsolbrig** [comment]
@evrose54 can you provide an update on the GLM reader, where it is located, and its status? Maybe this issue can be closed if your reader is working correctly, even if internally. I think we may want to transition the reader itself into core geoIPS when it is working correctly while keeping GREMLIN internal to CIRA for now.

**Comment by evrose54** [comment]
Sorry, I didn't see this comment. The GLM package I've created is located [here](https://bear.cira.colostate.edu/overcast/geoips_glm). It's currently stable and working, and is able to output Kyle's GREMLIN Products for GOES16-Full Disk, but can be modified if needed for different sectors contained within that region (ie. CONUS, South America, ...). The reader is working correctly, and can be transitioned into GeoIPS if wanted. @mindyls and @jsolbrig let me know if you'd like this and I can create a PR for this soon.

**Comment by jsolbrig** [comment]
This is complete in an internal repo. Will create a new issue to move the GLM reader into GeoIPS.

- [ ] Move GLM reader into core GeoIPS package from internal CIRA repo

**Comment by biosafetylvl5** [comment]
Done - creating new issue to move in. Related to #532
